"""Risk engine and risk modeling module for RakshakGIS."""

from app.core.risk.classification import (
    ClassificationBandConfigError,
    InvalidRiskScoreError,
    RiskBand,
    RiskClassificationEngine,
    RiskClassificationError,
    RiskClassificationExplainability,
    RiskClassificationResult,
    RiskScoreBandsConfig,
)
from app.core.risk.computation import (
    CompositeRiskExplainability,
    CompositeRiskResult,
    InsufficientFactorsError,
    InvalidFactorValueError,
    MultiHazardRiskEngine,
    REQUIRED_FACTORS,
    RiskComputationError,
    RiskComputationStatus,
    RiskFactorInput,
    RiskFactorType,
    RiskWeightsConfig,
    WeightConfigurationError,
)
from app.core.risk.normalization import (
    CategoricalSeverityPolicy,
    FactorCategory,
    InvalidInputError,
    LinearRangeConfig,
    NormalizationConfigError,
    NormalizationError,
    NormalizationExplainability,
    NormalizationMethod,
    NormalizationResult,
    NormalizationStatus,
    PiecewiseThresholdConfig,
    RiskNormalizationEngine,
    UnsupportedFactorError,
    categorical_severity_normalize,
    linear_normalize,
    piecewise_threshold_normalize,
)

__all__ = [
    # M3-05 Normalization
    "CategoricalSeverityPolicy",
    "FactorCategory",
    "InvalidInputError",
    "LinearRangeConfig",
    "NormalizationConfigError",
    "NormalizationError",
    "NormalizationExplainability",
    "NormalizationMethod",
    "NormalizationResult",
    "NormalizationStatus",
    "PiecewiseThresholdConfig",
    "RiskNormalizationEngine",
    "UnsupportedFactorError",
    "categorical_severity_normalize",
    "linear_normalize",
    "piecewise_threshold_normalize",
    # M3-06 Computation
    "CompositeRiskExplainability",
    "CompositeRiskResult",
    "InsufficientFactorsError",
    "InvalidFactorValueError",
    "MultiHazardRiskEngine",
    "REQUIRED_FACTORS",
    "RiskComputationError",
    "RiskComputationStatus",
    "RiskFactorInput",
    "RiskFactorType",
    "RiskWeightsConfig",
    "WeightConfigurationError",
    # M3-07 Classification
    "ClassificationBandConfigError",
    "InvalidRiskScoreError",
    "RiskBand",
    "RiskClassificationEngine",
    "RiskClassificationError",
    "RiskClassificationExplainability",
    "RiskClassificationResult",
    "RiskScoreBandsConfig",
]
