"""initial_schema

Revision ID: 7f762509fde4
Revises: 
Create Date: 2026-09-04 10:29:23.271851+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7f762509fde4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('endpoint_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('polling_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=True)
    op.create_table('disaster_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('disaster_type', sa.String(length=50), nullable=False),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('epicenter_or_center', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('affected_area', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('estimated_losses_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disaster_events_affected_area', 'disaster_events', ['affected_area'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index('idx_disaster_events_epicenter_or_center', 'disaster_events', ['epicenter_or_center'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_disaster_events_declared_at'), 'disaster_events', ['declared_at'], unique=False)
    op.create_index(op.f('ix_disaster_events_disaster_type'), 'disaster_events', ['disaster_type'], unique=False)
    op.create_index(op.f('ix_disaster_events_id'), 'disaster_events', ['id'], unique=False)
    op.create_index(op.f('ix_disaster_events_title'), 'disaster_events', ['title'], unique=False)
    op.create_table('hazard_layers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hazard_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('resolution_m', sa.Float(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazard_layers_hazard_type'), 'hazard_layers', ['hazard_type'], unique=False)
    op.create_index(op.f('ix_hazard_layers_id'), 'hazard_layers', ['id'], unique=False)
    op.create_index(op.f('ix_hazard_layers_name'), 'hazard_layers', ['name'], unique=False)
    op.create_table('rainfall_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=False),
    sa.Column('station_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('cumulative_24h_mm', sa.Float(), nullable=True),
    sa.Column('cumulative_72h_mm', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rainfall_records_station_location', 'rainfall_records', ['station_location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_rainfall_records_id'), 'rainfall_records', ['id'], unique=False)
    op.create_index(op.f('ix_rainfall_records_recorded_at'), 'rainfall_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_rainfall_records_station_id'), 'rainfall_records', ['station_id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regions_boundary', 'regions', ['boundary'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('payload_before_json', sa.JSON(), nullable=True),
    sa.Column('payload_after_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('data_ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('records_ingested', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_ingestion_runs_data_source_id'), 'data_ingestion_runs', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_data_ingestion_runs_id'), 'data_ingestion_runs', ['id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('headquarters', sa.String(length=100), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_districts_boundary', 'districts', ['boundary'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=True)
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_index(op.f('ix_districts_region_id'), 'districts', ['region_id'], unique=False)
    op.create_table('officer_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('action_taken', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('overridden_recommendation', sa.Boolean(), nullable=False),
    sa.Column('decision_metadata_json', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officer_decisions_decided_at'), 'officer_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_officer_decisions_decision_type'), 'officer_decisions', ['decision_type'], unique=False)
    op.create_index(op.f('ix_officer_decisions_id'), 'officer_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_officer_decisions_officer_id'), 'officer_decisions', ['officer_id'], unique=False)
    op.create_table('red_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('danger_level', sa.String(length=30), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('area_sq_km', sa.Float(), nullable=True),
    sa.Column('declared_by_officer_id', sa.Integer(), nullable=True),
    sa.Column('declared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['declared_by_officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_red_zones_geometry', 'red_zones', ['geometry'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_red_zones_id'), 'red_zones', ['id'], unique=False)
    op.create_index(op.f('ix_red_zones_is_active'), 'red_zones', ['is_active'], unique=False)
    op.create_index(op.f('ix_red_zones_name'), 'red_zones', ['name'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rainfall_multiplier', sa.Float(), nullable=False),
    sa.Column('seismic_intensity_mmi', sa.Float(), nullable=True),
    sa.Column('road_blockage_percentage', sa.Float(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_scenarios_name'), 'scenarios', ['name'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blocks_boundary', 'blocks', ['boundary'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_blocks_code'), 'blocks', ['code'], unique=True)
    op.create_index(op.f('ix_blocks_district_id'), 'blocks', ['district_id'], unique=False)
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_index(op.f('ix_blocks_name'), 'blocks', ['name'], unique=False)
    op.create_table('candidate_sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('area_sq_m', sa.Float(), nullable=True),
    sa.Column('terrain_slope_deg', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('suitability_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_sites_boundary', 'candidate_sites', ['boundary'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index('idx_candidate_sites_location', 'candidate_sites', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_candidate_sites_district_id'), 'candidate_sites', ['district_id'], unique=False)
    op.create_index(op.f('ix_candidate_sites_id'), 'candidate_sites', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_sites_name'), 'candidate_sites', ['name'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('executed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('simulated_affected_villages', sa.Integer(), nullable=True),
    sa.Column('simulated_displaced_population', sa.Integer(), nullable=True),
    sa.Column('results_summary_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_runs_id'), 'scenario_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_runs_scenario_id'), 'scenario_runs', ['scenario_id'], unique=False)
    op.create_table('infrastructure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('infra_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('capacity_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['candidate_sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_infrastructure_location', 'infrastructure', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_infrastructure_id'), 'infrastructure', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_name'), 'infrastructure', ['name'], unique=False)
    op.create_index(op.f('ix_infrastructure_site_id'), 'infrastructure', ['site_id'], unique=False)
    op.create_table('site_capacities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('max_households', sa.Integer(), nullable=False),
    sa.Column('max_population', sa.Integer(), nullable=False),
    sa.Column('allocated_households', sa.Integer(), nullable=False),
    sa.Column('allocated_population', sa.Integer(), nullable=False),
    sa.Column('available_households', sa.Integer(), nullable=False),
    sa.Column('available_population', sa.Integer(), nullable=False),
    sa.Column('water_supply_lpd', sa.Float(), nullable=True),
    sa.Column('sanitation_units', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['candidate_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_capacities_id'), 'site_capacities', ['id'], unique=False)
    op.create_index(op.f('ix_site_capacities_site_id'), 'site_capacities', ['site_id'], unique=False)
    op.create_table('villages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('census_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('slope_deg', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_villages_boundary', 'villages', ['boundary'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index('idx_villages_location', 'villages', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_villages_block_id'), 'villages', ['block_id'], unique=False)
    op.create_index(op.f('ix_villages_census_code'), 'villages', ['census_code'], unique=True)
    op.create_index(op.f('ix_villages_id'), 'villages', ['id'], unique=False)
    op.create_index(op.f('ix_villages_name'), 'villages', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_district_id'), 'alerts', ['district_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_acknowledged'), 'alerts', ['is_acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_issued_at'), 'alerts', ['issued_at'], unique=False)
    op.create_index(op.f('ix_alerts_village_id'), 'alerts', ['village_id'], unique=False)
    op.create_table('flood_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('inundation_polygon', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('peak_water_level_m', sa.Float(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('flood_type', sa.String(length=50), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=False),
    sa.Column('affected_population', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flood_events_inundation_polygon', 'flood_events', ['inundation_polygon'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_flood_events_event_date'), 'flood_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_flood_events_id'), 'flood_events', ['id'], unique=False)
    op.create_index(op.f('ix_flood_events_village_id'), 'flood_events', ['village_id'], unique=False)
    op.create_table('hazard_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('hazard_type', sa.String(length=50), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('intensity_value', sa.Float(), nullable=True),
    sa.Column('intensity_unit', sa.String(length=30), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hazard_observations_location', 'hazard_observations', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_hazard_observations_hazard_type'), 'hazard_observations', ['hazard_type'], unique=False)
    op.create_index(op.f('ix_hazard_observations_id'), 'hazard_observations', ['id'], unique=False)
    op.create_index(op.f('ix_hazard_observations_observed_at'), 'hazard_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_hazard_observations_village_id'), 'hazard_observations', ['village_id'], unique=False)
    op.create_table('landslide_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('scar_polygon', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('impact_summary', sa.Text(), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=False),
    sa.Column('displaced_persons', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_landslide_events_location', 'landslide_events', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index('idx_landslide_events_scar_polygon', 'landslide_events', ['scar_polygon'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_landslide_events_event_date'), 'landslide_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_landslide_events_id'), 'landslide_events', ['id'], unique=False)
    op.create_index(op.f('ix_landslide_events_village_id'), 'landslide_events', ['village_id'], unique=False)
    op.create_table('population_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=False),
    sa.Column('households', sa.Integer(), nullable=False),
    sa.Column('elderly_count', sa.Integer(), nullable=False),
    sa.Column('children_count', sa.Integer(), nullable=False),
    sa.Column('disabled_count', sa.Integer(), nullable=False),
    sa.Column('livestock_count', sa.Integer(), nullable=False),
    sa.Column('survey_year', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_population_profiles_id'), 'population_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_population_profiles_village_id'), 'population_profiles', ['village_id'], unique=True)
    op.create_table('relocation_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('candidate_site_id', sa.Integer(), nullable=False),
    sa.Column('assigned_households', sa.Integer(), nullable=False),
    sa.Column('assigned_population', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by_officer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_site_id'], ['candidate_sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relocation_assignments_candidate_site_id'), 'relocation_assignments', ['candidate_site_id'], unique=False)
    op.create_index(op.f('ix_relocation_assignments_id'), 'relocation_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_relocation_assignments_village_id'), 'relocation_assignments', ['village_id'], unique=False)
    op.create_table('relocation_priorities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('priority_band', sa.String(length=30), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('estimated_households', sa.Integer(), nullable=False),
    sa.Column('estimated_people', sa.Integer(), nullable=False),
    sa.Column('urgency_reason', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relocation_priorities_id'), 'relocation_priorities', ['id'], unique=False)
    op.create_index(op.f('ix_relocation_priorities_is_active'), 'relocation_priorities', ['is_active'], unique=False)
    op.create_index(op.f('ix_relocation_priorities_priority_band'), 'relocation_priorities', ['priority_band'], unique=False)
    op.create_index(op.f('ix_relocation_priorities_village_id'), 'relocation_priorities', ['village_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=30), nullable=False),
    sa.Column('hazard_subscore', sa.Float(), nullable=False),
    sa.Column('exposure_subscore', sa.Float(), nullable=False),
    sa.Column('vulnerability_subscore', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_band'), 'risk_scores', ['band'], unique=False)
    op.create_index(op.f('ix_risk_scores_calculated_at'), 'risk_scores', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_index(op.f('ix_risk_scores_is_current'), 'risk_scores', ['is_current'], unique=False)
    op.create_index(op.f('ix_risk_scores_village_id'), 'risk_scores', ['village_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('origin_village_id', sa.Integer(), nullable=False),
    sa.Column('destination_site_id', sa.Integer(), nullable=False),
    sa.Column('path', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_travel_time_min', sa.Float(), nullable=True),
    sa.Column('route_type', sa.String(length=50), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blockage_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_site_id'], ['candidate_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routes_path', 'routes', ['path'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_routes_destination_site_id'), 'routes', ['destination_site_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_is_blocked'), 'routes', ['is_blocked'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    op.create_index(op.f('ix_routes_origin_village_id'), 'routes', ['origin_village_id'], unique=False)
    op.create_table('vulnerability_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('social_vulnerability_index', sa.Float(), nullable=False),
    sa.Column('economic_vulnerability_index', sa.Float(), nullable=False),
    sa.Column('structural_vulnerability_index', sa.Float(), nullable=False),
    sa.Column('road_connectivity_index', sa.Float(), nullable=False),
    sa.Column('composite_vulnerability_score', sa.Float(), nullable=False),
    sa.Column('factors_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_profiles_id'), 'vulnerability_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_vulnerability_profiles_village_id'), 'vulnerability_profiles', ['village_id'], unique=True)
    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=False),
    sa.Column('factor_name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factors_id'), 'risk_factors', ['id'], unique=False)
    op.create_index(op.f('ix_risk_factors_risk_score_id'), 'risk_factors', ['risk_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_factors_risk_score_id'), table_name='risk_factors')
    op.drop_index(op.f('ix_risk_factors_id'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_vulnerability_profiles_village_id'), table_name='vulnerability_profiles')
    op.drop_index(op.f('ix_vulnerability_profiles_id'), table_name='vulnerability_profiles')
    op.drop_table('vulnerability_profiles')
    op.drop_index(op.f('ix_routes_origin_village_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_is_blocked'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_site_id'), table_name='routes')
    op.drop_index('idx_routes_path', table_name='routes', postgresql_using='gist', if_exists=True)
    op.drop_table('routes')
    op.drop_index(op.f('ix_risk_scores_village_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_is_current'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_calculated_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_band'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_relocation_priorities_village_id'), table_name='relocation_priorities')
    op.drop_index(op.f('ix_relocation_priorities_priority_band'), table_name='relocation_priorities')
    op.drop_index(op.f('ix_relocation_priorities_is_active'), table_name='relocation_priorities')
    op.drop_index(op.f('ix_relocation_priorities_id'), table_name='relocation_priorities')
    op.drop_table('relocation_priorities')
    op.drop_index(op.f('ix_relocation_assignments_village_id'), table_name='relocation_assignments')
    op.drop_index(op.f('ix_relocation_assignments_id'), table_name='relocation_assignments')
    op.drop_index(op.f('ix_relocation_assignments_candidate_site_id'), table_name='relocation_assignments')
    op.drop_table('relocation_assignments')
    op.drop_index(op.f('ix_population_profiles_village_id'), table_name='population_profiles')
    op.drop_index(op.f('ix_population_profiles_id'), table_name='population_profiles')
    op.drop_table('population_profiles')
    op.drop_index(op.f('ix_landslide_events_village_id'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_id'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_event_date'), table_name='landslide_events')
    op.drop_index('idx_landslide_events_scar_polygon', table_name='landslide_events', postgresql_using='gist', if_exists=True)
    op.drop_index('idx_landslide_events_location', table_name='landslide_events', postgresql_using='gist', if_exists=True)
    op.drop_table('landslide_events')
    op.drop_index(op.f('ix_hazard_observations_village_id'), table_name='hazard_observations')
    op.drop_index(op.f('ix_hazard_observations_observed_at'), table_name='hazard_observations')
    op.drop_index(op.f('ix_hazard_observations_id'), table_name='hazard_observations')
    op.drop_index(op.f('ix_hazard_observations_hazard_type'), table_name='hazard_observations')
    op.drop_index('idx_hazard_observations_location', table_name='hazard_observations', postgresql_using='gist', if_exists=True)
    op.drop_table('hazard_observations')
    op.drop_index(op.f('ix_flood_events_village_id'), table_name='flood_events')
    op.drop_index(op.f('ix_flood_events_id'), table_name='flood_events')
    op.drop_index(op.f('ix_flood_events_event_date'), table_name='flood_events')
    op.drop_index('idx_flood_events_inundation_polygon', table_name='flood_events', postgresql_using='gist', if_exists=True)
    op.drop_table('flood_events')
    op.drop_index(op.f('ix_alerts_village_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_issued_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_acknowledged'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_district_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_villages_name'), table_name='villages')
    op.drop_index(op.f('ix_villages_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_census_code'), table_name='villages')
    op.drop_index(op.f('ix_villages_block_id'), table_name='villages')
    op.drop_index('idx_villages_location', table_name='villages', postgresql_using='gist', if_exists=True)
    op.drop_index('idx_villages_boundary', table_name='villages', postgresql_using='gist', if_exists=True)
    op.drop_table('villages')
    op.drop_index(op.f('ix_site_capacities_site_id'), table_name='site_capacities')
    op.drop_index(op.f('ix_site_capacities_id'), table_name='site_capacities')
    op.drop_table('site_capacities')
    op.drop_index(op.f('ix_infrastructure_site_id'), table_name='infrastructure')
    op.drop_index(op.f('ix_infrastructure_name'), table_name='infrastructure')
    op.drop_index(op.f('ix_infrastructure_id'), table_name='infrastructure')
    op.drop_index('idx_infrastructure_location', table_name='infrastructure', postgresql_using='gist', if_exists=True)
    op.drop_table('infrastructure')
    op.drop_index(op.f('ix_scenario_runs_scenario_id'), table_name='scenario_runs')
    op.drop_index(op.f('ix_scenario_runs_id'), table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index(op.f('ix_candidate_sites_name'), table_name='candidate_sites')
    op.drop_index(op.f('ix_candidate_sites_id'), table_name='candidate_sites')
    op.drop_index(op.f('ix_candidate_sites_district_id'), table_name='candidate_sites')
    op.drop_index('idx_candidate_sites_location', table_name='candidate_sites', postgresql_using='gist', if_exists=True)
    op.drop_index('idx_candidate_sites_boundary', table_name='candidate_sites', postgresql_using='gist', if_exists=True)
    op.drop_table('candidate_sites')
    op.drop_index(op.f('ix_blocks_name'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_district_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_code'), table_name='blocks')
    op.drop_index('idx_blocks_boundary', table_name='blocks', postgresql_using='gist', if_exists=True)
    op.drop_table('blocks')
    op.drop_index(op.f('ix_scenarios_name'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_red_zones_name'), table_name='red_zones')
    op.drop_index(op.f('ix_red_zones_is_active'), table_name='red_zones')
    op.drop_index(op.f('ix_red_zones_id'), table_name='red_zones')
    op.drop_index('idx_red_zones_geometry', table_name='red_zones', postgresql_using='gist', if_exists=True)
    op.drop_table('red_zones')
    op.drop_index(op.f('ix_officer_decisions_officer_id'), table_name='officer_decisions')
    op.drop_index(op.f('ix_officer_decisions_id'), table_name='officer_decisions')
    op.drop_index(op.f('ix_officer_decisions_decision_type'), table_name='officer_decisions')
    op.drop_index(op.f('ix_officer_decisions_decided_at'), table_name='officer_decisions')
    op.drop_table('officer_decisions')
    op.drop_index(op.f('ix_districts_region_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_index('idx_districts_boundary', table_name='districts', postgresql_using='gist', if_exists=True)
    op.drop_table('districts')
    op.drop_index(op.f('ix_data_ingestion_runs_id'), table_name='data_ingestion_runs')
    op.drop_index(op.f('ix_data_ingestion_runs_data_source_id'), table_name='data_ingestion_runs')
    op.drop_table('data_ingestion_runs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_index('idx_regions_boundary', table_name='regions', postgresql_using='gist', if_exists=True)
    op.drop_table('regions')
    op.drop_index(op.f('ix_rainfall_records_station_id'), table_name='rainfall_records')
    op.drop_index(op.f('ix_rainfall_records_recorded_at'), table_name='rainfall_records')
    op.drop_index(op.f('ix_rainfall_records_id'), table_name='rainfall_records')
    op.drop_index('idx_rainfall_records_station_location', table_name='rainfall_records', postgresql_using='gist', if_exists=True)
    op.drop_table('rainfall_records')
    op.drop_index(op.f('ix_hazard_layers_name'), table_name='hazard_layers')
    op.drop_index(op.f('ix_hazard_layers_id'), table_name='hazard_layers')
    op.drop_index(op.f('ix_hazard_layers_hazard_type'), table_name='hazard_layers')
    op.drop_table('hazard_layers')
    op.drop_index(op.f('ix_disaster_events_title'), table_name='disaster_events')
    op.drop_index(op.f('ix_disaster_events_id'), table_name='disaster_events')
    op.drop_index(op.f('ix_disaster_events_disaster_type'), table_name='disaster_events')
    op.drop_index(op.f('ix_disaster_events_declared_at'), table_name='disaster_events')
    op.drop_index('idx_disaster_events_epicenter_or_center', table_name='disaster_events', postgresql_using='gist', if_exists=True)
    op.drop_index('idx_disaster_events_affected_area', table_name='disaster_events', postgresql_using='gist', if_exists=True)
    op.drop_table('disaster_events')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
